version: '3.7'
services:
  go-app:
    build:
      args:
        http_port: ${HTTP_PORT}
        debug_port: ${DELVE_DEBUG_PORT}
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./storage/logs:/usr/app/storage/logs
    working_dir: /usr/app
    environment:
      DELVE_DEBUG_PORT: ${DELVE_DEBUG_PORT}
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "host=${DB_HOST} user=${DB_USERNAME} password=${DB_PASSWORD} dbname=${DB_DATABASE} port=${DB_PORT} sslmode=disable TimeZone=Europe/Moscow"
    ports:
      - ${HOST_HTTP_PORT}:${HTTP_PORT}
      - ${DELVE_DEBUG_PORT}:${DELVE_DEBUG_PORT}
    depends_on:
      - db

  db:
    image: postgres:16.1
    restart: always
    volumes:
      - ./storage/docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT_IDE}:5432
